{% set name = "jump" %}
{% set version = "0.1" %}
{% set hash = "3b124d3a818392d7703a7cf756a7139993b7e26e1a2a4bd650a6328600afe785" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/olllom/{{ name }}/tarball/{{ version }}
  sha256: {{ hash }}

build:
  noarch: python 
  number: 1
  script: "{{ PYTHON }} setup.py install"

requirements:
  host:
    - python 
    - setuptools >=0.7
    - plumbum
    - click >=6.0

  run:
    - python
    - plumbum >=1.5
    - click >=6.0

test:
  imports:
    - jump
  commands:
    - jump --help

about:
  home: https://github.com/Olllom/jump
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Running remote jupyter notebooks in a local browser window.'

extra:
  recipe-maintainers:
    - Olllom
