package:
  name: "jump"
  version: "0.1"

source:
  url: https://github.com/olllom/jump/archive/0.1.tar.gz
  sha256: {{ 7678f454c209fd7418c5dbf6afa61fd7deeefd97d6e3a60dc990655cad6fdc01 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - jump = jump.jump:main

requirements:
  host:
    - python >=3.5
    - setuptools >=0.7
    - plumbum
    - pip
    - click >=6.0

  run:
    - python >=3.5
    - plumbum >=1.5
    - click >=6.0

test:
  imports:
    - jump
  commands:
    - jump --help

about:
  home: https://github.com/Olllom/jump
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Running remote jupyter notebooks in a local browser window.'

extra:
  recipe-maintainers:
    - Olllom
