travis:
  secure:
    BINSTAR_TOKEN: NbcFoguFTvzNx2XTTxss2XjkHImE5ZTwHJzrTUs9T9YC2nU3ae4xcX4RxRhGe/8guU9izVHwHM1B1EzAHthFOi9wO3VuDPrBX86JPwnI2Jrgt/rIkVmrUUvgATfarwNweOr3Z0u+cTYAv61wqM+JSGgZahdu4OC8jeYiYSRrM8xYDQesiT7bkdUvap8k4A6sSN1Ew4scilr5oPwKr8kTeBXVxh4EiX2bDcE5h9CQD72zYNMGirUn5acE9fCxKhgLXBIpIWObx8KJ96FywMrFQ4pppWQY+p+tg+r542zEkZpXR0+UIGE/TYYiQZg8am5Qc/8DhRnQAbxIJy83uJoKxZylPfHx8cDXzGT8tPkSonMgQIR+/bahmvS1bS7Xg6PmuKLj9HkzvVz49/NswjPb36hm1kIeBY6x9DmgNpkbfUQq7o06c7955ifAmxIx2Z65Bn8LMd5oitzOjgPxVNqp8gaWvEbV7+r6K1BbUzu/GxrEI7hk4nWB6A09tAldQg/tCKOKvKW9LS/HDO0URlvGedupv8YZQSXyosQyRHr4g0C8H870o0mGJjgiWFTltd02srN+E6kC8ymGvUbPqxB1JhGjfwcRg4LFT+NMBoCqVhI6MsVldKF/DVJquDyVMvfy6i0xE8rajz2qr99KYCoUJQbZTnKNqukLouZMqufVrKI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
win:
  enabled: False
min_py_ver: '35'
max_py_ver: '37'
